### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anup-a** [anup-a/CosmicLMS#4]
- [ ] Check for Private?Unavailable videos while uploading playlist

- [ ] Validation option for uploaded YouTube Playlist

- [ ] Enhancement - Fetch Playlist and Video Thumbnail

- [ ] Display and Automate Playlist description

- [ ] Fix default Language to English (Currently it is displaying Afrikaans) 

- [ ] Sort the Listed Videos by initial Order/added Order

- [ ] Important - Activity Enroll/Search Option ( Currently function is limited to Course )
